### ISSUE TITLE
support class and protocols extensions

### ISSUE THREAD

**Issue by smamczak** [Sumolari/swift-relationship-graph#2]
Hi, It would be nice to add support for extensions in graph.
When I definde class like so
```
class Foo: FooParentClass, BarProtocol {
    func foo() {}
    func bar() {}
}
```
sourcekitten gives me
```
"key.name" : "Foo",
"key.inheritedtypes" : [
    {
        "key.name" : "FooParentClass"
    },
    {
        "key.name" : "BarProtocol"
    }
],
```
and graph looks good, but when I do something like this
```
class Foo: FooParentClass {
    func foo() { }
}

extension Foo: BarProtocol {
    func bar() {}
}
```
this generate in sourcekitten 2 entries
```
"key.name" : "Foo",
"key.inheritedtypes" : [
   {
        "key.name" : "FooParentClass"
    }
],

...

"key.name" : "Foo",
"key.inheritedtypes" : [
    {
        "key.name" : "BarProtocol"
    }
],
```
and there is no connection in graph between **Foo** and **BarProtocol**

**Comment by Sumolari** [comment]
Hi!

Thanks for the suggestion. I'll try to implement it as soon as possible but I'm quite busy these days and it might took me a while to have it.

Meanwhile if you prefer to implement it and create a pull request, I'll gladly merge it.

In any case I'll keep you posted about this issue :)

**Comment by Sumolari** [comment]
@smamczak Could you check [extensions](https://github.com/Sumolari/swift-relationship-graph/pull/3) branch? I think it solves this issue.

**Comment by smamczak** [comment]
Hi @Sumolari I've checked [extensions](https://github.com/Sumolari/swift-relationship-graph/pull/3) branch and It's exactly what I wanted. Thanks!

**Comment by Sumolari** [comment]
Great. I'm merging the branch and closing this issue :)
